title: Xinzhuo Li's Homepage
page-top-title: Xinzhuo Li
top-section-bg-text: Electrical and Computer Engineering
home-subtitle: Xinzhuo Li&ensp;|&ensp;李昕卓
copyright-text: '&copy; Xinzhuo Li 2024-2025. All Rights Reserved.'
